version: '3.8'

services:
  ml_app:
    build: .
    ports:
      - "5000:5000"  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/app/mlruns  

  mlflow:
    image: mlflow/mlflow
    ports:
      - "5000:5000"  
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow  
